version: '3.9'

services:
  # Include the PHP-FPM and Nginx services
  php:
    image: php:8.1-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - ${DB_ENGINE:-mysql}

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT:-8000}:80"
    depends_on:
      - php
