version: '3.8'

services:
  # Update backend database connection
  backend:
    environment:
      DB_CONNECTION: "mysql"
      DB_PORT: "3306"

  # MySQL database configuration  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin configuration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: "db"
      PMA_PORT: "3306" 