name: CI

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install ChimeraStack CLI in editable mode
        run: pip install -e .
      - name: Run unit tests (fast suite)
        run: |
          pytest -m "not integration" -q
      - name: Build package
        run: |
          python -m pip install build
          python -m build
